### ISSUE TITLE
References about your Apps

### ISSUE THREAD

**Issue by rengz-code** [kshedstrom/Apps_master#1]
Hello, Professor. 
I'm curious about your biological applications with ROMS, especially the fish model. I also want to make the fish models and then do some scientific research. I'm so happy that I can find your github account today. Could you please give us some reference articles about your applications that you put on the github?

**Comment by kshedstrom** [comment]
The fish publications are listed here: [https://www.uaf.edu/cfos/research/projects/end-to-end-fish-model/index.php](https://www.uaf.edu/cfos/research/projects/end-to-end-fish-model/index.php). Professor Fiechter has run this more recently than I have and he would have the latest fish code. That said, the limitation of it is in the parallel implementation. The way to do better is to write an offline code and make it parallel by fish, not by tile.

**Comment by rengz-code** [comment]
Thank you very much!
